### ISSUE TITLE
"brand" schema element is missing @type for Product ItemType

### ISSUE THREAD

**Issue by JoseAFerrete** [Dudo1985/Yet-Another-Stars-Rating#1]
Following [Google's Product schema guide](https://developers.google.com/search/docs/advanced/structured-data/product) show that the brand property should be formed with @type and name:
![image](https://user-images.githubusercontent.com/43861978/180171788-57b4fd0d-b6cd-4749-9c7b-6d762387a191.png)

Currently the function YasrRichSnippets->itemProduct() only sets "brand" using `$post_meta['yasr_product_brand']`

Working on a PR.

**Comment by joseEkcit** [comment]
Created a pull request here: https://github.com/Dudo1985/Yet-Another-Stars-Rating/pull/2

**Comment by JoseAFerrete** [comment]
Created a pull request here: https://github.com/Dudo1985/Yet-Another-Stars-Rating/pull/2

**Comment by Dudo1985** [comment]
Thank you, this is done with commit https://github.com/Dudo1985/Yet-Another-Stars-Rating/commit/eefe7b385d44e44737c2b37398216979ebe8e084 !
