### ISSUE TITLE
star rating not showing.

### ISSUE THREAD

**Issue by iamwahabrana** [Dudo1985/Yet-Another-Stars-Rating#4]
Star icons not showing can you please let me know what is the issue?
![2023-01-30_0-16-56](https://user-images.githubusercontent.com/123899349/215350627-4d8c8c1a-0a2d-4751-beac-1af48a564fbb.png)

here is the [link](shorturl.at/eLMY1)

**Comment by Dudo1985** [comment]
Hello, most probably is caused by a conflict with the theme, I see there is a js error in the console.
Try to fix that error first, then it should work.

Best,
Dario

**Comment by iamwahabrana** [comment]
js errors fixed. but still not showing.

**Comment by Dudo1985** [comment]
Seems like the js is not loaded att all, must be a conflict with another plugin or the theme itself

**Comment by iamwahabrana** [comment]
I disabled all the plugins but haven't solved the issue. it is theme confit. how to load the js file manually? or how to solve this issue? is there any way to check?

**Comment by iamwahabrana** [comment]
can you help me to solve this issue?

**Comment by Dudo1985** [comment]
Hello, 
please do not bump the threads: it just slow down my queue, I always answer ASAP.

To answer your question, I see you're using a custom theme, and it is impossible for me to do some tests.

Best,
Dario

**Comment by Dudo1985** [comment]
Hello!

If you're using the_excerpt() in your theme, can you try to add [this code](https://gist.github.com/Dudo1985/9a75621ffb7cb72b0e910c31ff455e93) in your functions.php ? 

Let me know!

**Comment by iamwahabrana** [comment]
I found the solution you add your js files in the footer. in the theme wp_footer was missing. so I added it and worked. 
but now I used your plugin for rich snippets I got some reviews but haven't found any review structure data. also, there is no json code for review nor microdata for review

**Comment by Dudo1985** [comment]
Great! 

About rich snippets, did you set to "no" at "Is this a review?"

You can find all the info [here](https://yetanotherstarsrating.com/yasr-rich-snippets/)

**Comment by iamwahabrana** [comment]
I try both options but didn't work. JSON code is not in the custom post type.
