### ISSUE TITLE
Display shortcode via AJAX

### ISSUE THREAD

**Issue by flexcodenet** [Dudo1985/Yet-Another-Stars-Rating#5]
Hello.

While i load poast via AJAX, shortcode dosen't display form raiting.

I use function do_shortcode and [yasr_visitor_votes size="small"].
I tried set postid in shortcode but dosen't help too.

Can't they be used like this?

**Comment by Dudo1985** [comment]
Hello!

Once the ajax call is done, you've to call the  `yasrSearchVVInDom` function.

[Here](https://github.com/Dudo1985/Yet-Another-Stars-Rating/blob/master/includes/js/src/catch-inifite-scroll.js) you can see how I did for adding support to Infinite Scroll plugin, which is supported.

Best,
Dario

**Comment by flexcodenet** [comment]
Hello Dario.

The function is available in the DOM?

**Comment by flexcodenet** [comment]
> Hello!
> 
> Once the ajax call is done, you've to call the `yasrSearchVVInDom` function.
> 
> [Here](https://github.com/Dudo1985/Yet-Another-Stars-Rating/blob/master/includes/js/src/catch-inifite-scroll.js) you can see how I did for adding support to Infinite Scroll plugin, which is supported.
> 
> Best, Dario

In my html i dont see rendered class 'yasr-rater-stars-vv' - string is empty.

**Comment by Dudo1985** [comment]
Hi, sorry for the delay of the answer.

[That class is declared when the shortcode is returned](https://github.com/Dudo1985/Yet-Another-Stars-Rating/blob/master/includes/shortcodes/classes/YasrVisitorVotes.php#L360) , so I guess that the code you're using strip some html output in the ajax response

**Comment by flexcodenet** [comment]
Hello. I tested this problem again.

My shortcode is generating correctly. Here is a screenshot:
![Zrzut ekranu 2023-03-23 113546](https://user-images.githubusercontent.com/47887928/227177796-e878f8cf-5a3a-4876-9a6a-98c4542f234b.jpg)

My code in single:
![Zrzut ekranu 2023-03-23 113744](https://user-images.githubusercontent.com/47887928/227178146-eef25348-fed8-4093-9ca6-ebc5f4f291f9.png)

First load - correct. While i load next post via AJAX, function stopped work. I can't click on the stars and change the rating or vote. Before running ajax, I can.

The second problem is, while i load post via AJAX, shortcode does not generate plugin code. - empty div:
![image](https://user-images.githubusercontent.com/47887928/227179184-48fc2b75-cb70-4077-a1ed-ca72a39a908e.png)

I am using the Contact Form 7 shortcode above, everything works fine, it generates it every time the next post is loaded.

**Comment by flexcodenet** [comment]
@Dudo1985 Cloud you check these problem again?

**Comment by flexcodenet** [comment]
@Dudo1985 
I cant set in AJAX is_singular = true.
![image](https://user-images.githubusercontent.com/47887928/227191302-9362928b-dd5f-4fea-b0a2-6fb51eb95d6b.png)
Therefore, the shortcode is not displayed.
